---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u9073895/public_html/
    - /bin/cp -R components $DEPLOYPATH
    - /bin/cp -R core $DEPLOYPATH
    - /bin/cp -R pages $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp LICENSE $DEPLOYPATH
    - /bin/cp next-env.d.ts $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp postcss.config.js $DEPLOYPATH
    - /bin/cp tailwind.config.js $DEPLOYPATH
    - /bin/cp tsconfig.json $DEPLOYPATH
